<?php

namespace AppBundle\Repository;

/**
 * ActorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ActorRepository extends \Doctrine\ORM\EntityRepository
{
    public function findTestActors()
    {
        return $this->createQueryBuilder('Actor')
            ->select('Actor')
            ->where('Actor.field = :t')
            ->setParameter('t', "TEST")
            ->getQuery()
            ->getResult();
    }

}
