<?php

namespace AppBundle\Repository;

/**
 * CompanyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CompanyRepository extends \Doctrine\ORM\EntityRepository
{
	public function create($company)
	{
		$em = $this->getEntityManager();
		$em->persist($company);
		$em->flush();
		return $company;
	}

	private function findCompaniesBySearch($searchTerm)
	{
		return $this->createQueryBuilder('Company')
			->select('Company')
			->where('Company.name LIKE :searchTerm')
			->orWhere('Company.location LIKE :searchTerm')
            ->orWhere('Company.field LIKE :searchTerm')
            ->orWhere('Company.competence LIKE :searchTerm')
            ->orWhere('Company.competence LIKE :searchTerm')
			->setParameter('searchTerm', '%'.$searchTerm.'%')
			->getQuery()
			->getResult();
	}

    public function findCompaniesBySearchArray(array $search)
    {
        $freetxtsearch = array(); // $fieldsearch
        foreach ($search as $s) {
            $freetxtsearch = array_merge($freetxtsearch, $this->findCompaniesBySearch($s));
        }
        $freetxtsearch = array_unique($freetxtsearch);
        return $freetxtsearch;
    }

	public function findCompaniesByType($type)
	{
		return $this->createQueryBuilder('Company')
			->select('Company')
			->where('Company.type = :type')
			->setParameter('type', $type)
			->getQuery()
			->getResult();
	}

	public function findCompanyByOrgNr($orgNr)
	{
		return $this->createQueryBuilder('Company')
			->select('Company')
			->where('Company.orgNr = :orgNr')
			->setParameter('orgNr', $orgNr)
			->getQuery()
			->getSingleResult();
	}

	public function findEditedCompanies()
	{
		return $this->createQueryBuilder('Company')
			->select('Company')
			->where('Company.version > 0')
			->getQuery()
			->getResult();
	}
	
}
