<?php

namespace AppBundle\Repository;

/**
 * MeasureRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MeasureRepository extends \Doctrine\ORM\EntityRepository
{
}
