app:
    resource: "@AppBundle/Controller/"
    type:     annotation

home:
    path: /
    defaults: { _controller: AppBundle:Home:showHome}

projectlist:
  path: /anlegg
  defaults: { _controller: AppBundle:ProjectList:projectList}

actorlist:
  path: /actor
  defaults: { _controller: AppBundle:ActorList:show }

login:
    path: /login
    defaults: { _controller: AppBundle:Login:login}

logout:
    path: /logout

create_user:
    path:     /register
    defaults: { _controller: AppBundle:User:register } 

create_person:
    path:     /person/ny
    defaults: {_controller: AppBundle:Person:create }

create_company:
    path:     /company/ny
    defaults: {_controller: AppBundle:Company:create }

project:
  path: /anlegg/{id}
  defaults: {_controller: AppBundle:Project:show}
  requirements:
    methods: GET|POST
    id: \d+

company:
  path: /selskap/{id}
  defaults: {_controller: AppBundle:Company:show}
  requirements:
    methods: GET|POST
    id: \d+

person:
  path: /person/{id}
  defaults: {_controller: AppBundle:Person:show}
  requirements:
    methods: GET|POST
    id: \d+

create_project:
  path:     /anlegg/ny
  defaults: { _controller: AppBundle:Project:create}

edit:
  path:     /rediger
  defaults: { _controller: AppBundle:EditList:show}

personalprofile:
  path:     /me
  defaults: { _controller: AppBundle:Profile:showMyProfile}

activate_users:
  path:     /me/activate
  defaults: { _controller: AppBundle:Profile:activateUsers}

deactivate_users:
  path:     /me/deactivate
  defaults: { _controller: AppBundle:Profile:deactivateUsers}

# View other's profile
publicprofile:
  path: /prof/{id}
  defaults: {_controller: AppBundle:Profile:showProfile}
  requirements:
    methods: GET|POST
    id: \d+

# Edit other's profile
editotherprofile:
  path: /rp/{id}
  defaults: {_controller: AppBundle:Profile:editProfile}
  requirements:
    methods: GET|POST
    id: \d+

userlist:
  path: /brukere
  defaults: { _controller: AppBundle:User:showAllUsers}

queryme:
  path:     /me/qp
  defaults: { _controller: AppBundle:Profile:queryMe}

edit_project:
  path:     /anlegg/rediger/{id}
  defaults: { _controller: AppBundle:Project:edit}
  requirements:
    methods: GET|POST
    id: \d+
