# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    encoders:
        AppBundle\Entity\User:
            algorithm: sha256
    role_hierarchy:
        ROLE_EDITOR: ROLE_USER
        ROLE_USER: IS_AUTHENTICATED_FULLY, ROLE_GUEST
        # See also: http://symfony.com/doc/current/security.html#roles
    providers:
        our_db_provider:
            entity:
                class: AppBundle:User
                property: email
                # not neccessary if UserRepository implements UserLoaderInterface
    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
          # pattern: ^/(_(profiler|wdt|error)|css|images|js)/
            security: false
        main:
            pattern: ^/
            anonymous: ~
            form_login:
                default_target_path: /
                always_use_default_target_path: true
                login_path: logginn
                check_path: logginn
            logout:
                path: loggut
                target: /
            # http_basic: ~
            # http://symfony.com/doc/current/book/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html
    access_control:
        - { path: ^/logginn, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/glemt-passord, roles: IS_AUTHENTICATED_ANONYMOUSLY }